<?xml version="1.0" encoding="UTF-8"?><testrun name="TestEmployeeDao" project="employeejdbc" tests="3" started="3" failures="2" errors="1" ignored="0">
  <testsuite name="com.nexturn.employee.testing.TestEmployeeDao" time="1.279" displayname="TestEmployeeDao" uniqueid="[engine:junit-jupiter]/[class:com.nexturn.employee.testing.TestEmployeeDao]">
    <testcase name="testAddEmployee" classname="com.nexturn.employee.testing.TestEmployeeDao" time="1.076" displayname="testAddEmployee()" uniqueid="[engine:junit-jupiter]/[class:com.nexturn.employee.testing.TestEmployeeDao]/[method:testAddEmployee()]">
      <error>com.nexturn.employee.exceptions.EmployeeCodeAlreadyExistException: Employee ID already exists enter another....&#13;
	at com.nexturn.employee.dao.EmployeeDaoImpl.addEmployee(EmployeeDaoImpl.java:33)&#13;
	at com.nexturn.employee.testing.TestEmployeeDao.testAddEmployee(TestEmployeeDao.java:25)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGetEmployeeById" classname="com.nexturn.employee.testing.TestEmployeeDao" time="0.08" displayname="testGetEmployeeById()" uniqueid="[engine:junit-jupiter]/[class:com.nexturn.employee.testing.TestEmployeeDao]/[method:testGetEmployeeById()]">
      <failure>org.opentest4j.AssertionFailedError: expected: not &lt;null&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)&#13;
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)&#13;
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)&#13;
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:304)&#13;
	at com.nexturn.employee.testing.TestEmployeeDao.testGetEmployeeById(TestEmployeeDao.java:48)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUpdateEmployee" classname="com.nexturn.employee.testing.TestEmployeeDao" time="0.119" displayname="testUpdateEmployee()" uniqueid="[engine:junit-jupiter]/[class:com.nexturn.employee.testing.TestEmployeeDao]/[method:testUpdateEmployee()]">
      <failure>
        <expected>1</expected>
        <actual>0</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;1&gt; but was: &lt;0&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)&#13;
	at com.nexturn.employee.testing.TestEmployeeDao.testUpdateEmployee(TestEmployeeDao.java:36)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
